const products = [
    { id: 1, name: "Рикордея желтая, М /Ricordea yuma (Pimple Mushroom Yellow - Per Leaf)", price: "11 900 ₽", image: "url('/images/image_1.png')", htmlId: "corals" },
    { id: 2, name: "Родактис волосатый в ассортименте, М /Rhodactis inchoata (coloured)", price: "6 500 ₽", image: "url('../images/image_2.png')" },
    { id: 3, name: "Родактис волосатый зеленый, М /Rhodactis indosinensis (green)", price: "3 990 ₽", image: "url('../images/image_3.png')" },
    { id: 4, name: "Рикордея многоцветная, М /Ricordea yuma (Multicolour)", price: "9 900 ₽", image: "url('../images/image_4.png')" },
    { id: 5, name: "Дискосомы разноцветные, М /Discosoma aasp.(coloured)", price: "5 900 ₽", image: "url('../images/image_5.png')" },
    { id: 7, name: "Рикордея Юма оранжевая/Ricordea yuma (Orange)", price: "S - 2 500/ M - 7 500 ₽", image: "url('../images/image_7.jpg')" },
    { id: 8, name: "Дискосомы зеленые/Discosoma coeruleostriatus (green)", price: "M - 4 500/ L - 7500 ₽", image: "url('../images/image_8.jpg')" },
    { id: 9, name: "Дискосома-слоновье ухо (дискоактинии), M /Amplexidiscus fenestrafer", price: "6 900 ₽", image: "url('../images/image_9.jpg')" },
    { id: 15, name: "Дискосома-слоновье ухо/Amplexidiscus fenestrafer", price: "L - 6 990/ M - 5 990 ₽", image: "url('../images/image_15.png')" },
    { id: 16, name: "Родактис волосатый зеленый, М/L /Rhodactis indosinensis (green) КЕНИЯ", price: "5 900 ₽", image: "url('../images/image_16.png')" },
    { id: 17, name: "Акантастрея зеленая, L /Acanthastrea lordhowensis(Green).", price: "12 900 ₽", image: "url('../images/image_17.jpg')" },
    { id: 18, name: "Бластомусса Уэллса мультиколор, M/Blastomussa wellsi (Multicolour).", price: "10 000 ₽", image: "url('../images/image_18.jpg')" },
    { id: 19, name: "Каталафиллия Жардена, M/Catalaphyllia jardinei(GREEN WITH COLORED TIP).", price: "8 990 ₽", image: "url('../images/image_19.jpg')" },
    { id: 20, name: "Эхинофиллия красная, L /Echinophyllia aasp. (red).", price: "10 900 ₽", image: "url('../images/image_20.jpg')" },
    { id: 21, name: "Эуфилия факельная золотая, M /Euphyllia glabrescens (Golden).", price: "25 000 ₽", image: "url('../images/image_21.jpg')" },
    { id: 22, name: "Эуфилия факельная, M /Euphyllia glabrescens (BABY TIGER BANANA).", price: "13 990 ₽", image: "url('../images/image_22.jpg')" },
    { id: 23, name: "ФРАГ Эуфилия лягушачья икра /Euphyllia divisa.", price: "3 500 ₽", image: "url('../images/image_23.jpg')" },
    { id: 24, name: "Эуфиллия молоточковая, M/Euphyllia ancora (Metallic Green)", price: "9 900 ₽", image: "url('../images/image_24.jpg')" },
    { id: 25, name: "Эуфиллия молоточковая зеленый металлик, M/Euphyllia paraancora (Metallic Green).", price: "9 000 ₽", image: "url('../images/image_25.jpg')" },
    { id: 26, name: "Эуфиллия молоточковая оранжевая, M /Euphyllia paraancora", price: "12 000 ₽", image: "url('../images/image_26.jpg')" },
    { id: 27, name: "Фавитес, M /Favites aasp.(MULTICOLOR)", price: "7 990 ₽", image: "url('../images/image_27.jpg')" },
    { id: 28, name: "Галаксия, M / Galaxea fascicularis", price: "5 000 ₽", image: "url('../images/image_28.jpg')" },
    { id: 29, name: "Гелиофунгия зеленый металлик, S /Heliofungia actiniformis(green metallic).", price: "4 900 ₽", image: "url('../images/image_29.jpg')" },
    { id: 30, name: "Гелиофунгия зеленый металлик, S /Heliofungia actiniformis(green metallic).", price: "4 900 ₽", image: "url('../images/image_30.jpg')" },
    { id: 31, name: "Лобофилия розовая, M /Lobophyllia Hemprichii (PINK).", price: "6 990 ₽", image: "url('../images/image_31.jpg')" },
    { id: 32, name: "Лобофилия мультиколор, M /Lobophyllia hemprichii (Multicolor).", price: "5 990 ₽", image: "url('../images/image_32.jpg')" },
    { id: 33, name: "Пузырчатый коралл плерогира(зеленый металлик), M /Plerogyra sinuosa(Metallic Green).", price: "7 990 ₽", image: "url('../images/image_33.jpg')" },
    { id: 34, name: "Пузырчатый коралл плерогира(желтая), M /Plerogyra sinuosa(Yellow)", price: "7 700 ₽", image: "url('../images/image_34.jpg')" },
    { id: 35, name: "Поритес, M /Porites Spp.(Multicolor worm coral)", price: "5 900 ₽", image: "url('../images/image_35.jpg')" },
    { id: 36, name: "Симфиллия разноцветная, M/L/Symphyllia aasp. (colored)", price: "9 900 ₽", image: "url('../images/image_36.jpg')" },
    { id: 37, name: "Трахифиллия Жофруа разноцветная, M /Trachyphyllia geoffroyi (Multi Colored).", price: "8 990 ₽", image: "url('../images/image_37.jpg')" },
    { id: 38, name: "Трахифиллия Жофруа(зеленая)", price: "8 990 ₽", image: "url('../images/image_38.jpg')" },
    { id: 39, name: "Велсофиллия радиата, M /Wellsophyllia radiata (GREEN METALLIC)", price: "7 990 ₽", image: "url('../images/image_39.jpg')" },
    { id: 40, name: "Тубастрея солнечная, М /Tubastrea (Orange)", price: "4 990 ₽", image: "url('../images/image_40.jpg')" },
    { id: 41, name: "Тубипора музыка зеленая, М/Tubipora musica(Green polyps)", price: "3 900 ₽", image: "url('../images/image_41.jpg')" },
    { id: 42, name: "Турбинария рениформис желтая, М /Turbinaria Reniformis (yellow)", price: "3 500 ₽", image: "url('../images/image_42.jpg')" },
    { id: 43, name: "Бластомусса Уэллса мультиколор, M/Blastomussa wellsi (Multicolour).", price: "10 000 ₽", image: "url('../images/image_43.jpg')" },
    { id: 44, name: "Велсофилия Жофруа(мультиколор), M /Wellosophyllia Geofroyi (Multicolor)", price: "15 000 ₽", image: "url('../images/image_44.jpg')" },
    { id: 45, name: "Альвеопора зеленая, M /Alveopora aasp(GREEN WITH COLORED TIP).", price: "8 000 ₽", image: "url('../images/image_45.jpg')" },
    { id: 46, name: "Цинарина зеленая, M /Cynarina lacrymalis (Green).", price: "6 000 ₽", image: "url('../images/image_46.jpg')" },
    { id: 47, name: "Индофиллия макассарская (коралл-пончик), M /Indophyllia macassarensis ( GREEN).", price: "9 000 ₽", image: "url('../images/image_47.jpg')" },
    { id: 48, name: "Акропора цветная, M /Acropora sp. (Cultured)", price: "15 000 ₽", image: "url('../images/image_48.jpg')" },
    { id: 49, name: "Альвеопора зеленый металлик, M /Alveopora spongiosa (METALLIC GREEN)", price: "4 000 ₽", image: "url('../images/image_49.jpg')" },
    { id: 50, name: "Фунгия зеленая, M /Fungia sp. (Green)", price: "5 500 ₽", image: "url('../images/image_50.jpg')" },
    { id: 51, name: "Полифилия кротовидная зеленая, M /Polyphyllia talpina (Green)", price: "3 000 ₽", image: "url('../images/image_51.jpg')" },
    { id: 52, name: "Платигира, M/Platygyra aasp.", price: "5 900 ₽", image: "url('../images/image_52.jpg')" },
    { id: 53, name: "Турбинария пелтата зеленая, M /Turbinaria peltata (GREEN)", price: "3 900 ₽", image: "url('../images/image_53.jpg')" },
    { id: 54, name: "Платигира, M/Platygyra aasp.", price: "5 900 ₽", image: "url('../images/image_54.jpg')" },
    { id: 55, name: "Бластомусса мерлетти, M /Blastomussa merleti", price: "6 000 ₽", image: "url('../images/image_55.jpg')" },
    { id: 56, name: "ФРАГ Эуфиллия молоточковая/Euphyllia parancora.", price: "3 500 ₽", image: "url('../images/image_56.jpg')" },
    { id: 57, name: "ФРАГ Эуфилия лягушачья икра/Euphyllia divisa.", price: "3 500 ₽", image: "url('../images/image_57.jpg')" },
    { id: 58, name: "ФРАГ Эуфилия факельная/Euphyllia glabrescens.", price: "от 5 000 ₽", image: "url('../images/image_58.jpg')" },
    { id: 59, name: "ФРАГ Монтипора цветная красная, L /Montipora", price: "2 500 ₽", image: "url('../images/image_59.jpg')" },
    { id: 60, name: "ФРАГ Акантастрея, Acanthastrea", price: "M - 4 000/S - 3 500 ₽", image: "url('../images/image_60.jpg')" },
    { id: 61, name: "Румфелла, М /Rumphella aggregata (cultured) КЕНИЯ", price: "5 900 ₽", image: "url('../images/image_61.jpg')" },
    { id: 62, name: "Зоантусы многоцветные, М /Zoanthus sp Multicolor", price: "12 000 ₽", image: "url('../images/image_62.jpg')" },
    { id: 63, name: "Политоя, M /Palythoa sp.", price: "3 000 ₽", image: "url('../images/image_63.jpg')" },
    { id: 64, name: "Зоантусы цветные, M /Zoanthus aasp. (colored)", price: "7 000 ₽", image: "url('../images/image_64.jpg')" },
    { id: 65, name: "Зоантусы красные, М /Zoanthus aasp. (Red).", price: "3 900 ₽", image: "url('../images/image_65.jpg')" },
    { id: 66, name: "Зоантусы цветные, L /Zoanthus aasp. (colored)", price: "13 000 ₽", image: "url('../images/image_66.jpg')" },
    { id: 67, name: "Клавулярия оранжевая гвоздика, M/Clavularia sp. (CLOVE POLYPS ORANGE)", price: "3 900 ₽", image: "url('../images/image_67.png')" },
    { id: 68, name: "Бриареум ковер зеленый, L /Briareum stechei", price: "L - 4 990\M - 3 200 ₽", image: "url('../images/image_68.png')" },
    { id: 69, name: "Клавулярия звездчатая, S /Pachyclavularia violacea (GREEN, WHITE TIP)", price: "4 500 ₽", image: "url('../images/image_69.png')" },
    { id: 70, name: "Клавулярия звездчатая зеленый металлик, M /Pachyclavularia violacea (Metalic green star polyp)", price: "4 900 ₽", image: "url('../images/image_70.png')" },
    { id: 71, name: "Кладиела, M/Cladiella sp.", price: "3 990 ₽", image: "url('../images/image_71.jpg')" },
    { id: 72, name: "Склеронефтия красная. M /Scleronephthya aasp.(RED).", price: "3 990 ₽", image: "url('../images/image_72.png')" },
    { id: 73, name: "Синулярия дура, M /Sinularia dura (Green)", price: "S - 2 500/ M - 2 900 ₽", image: "url('../images/image_73.png')" },
    { id: 74, name: "Клавулярия зеленая гвоздика, M/Clavularia sp. (Green Clove)", price: "9 000 ₽", image: "url('../images/image_74.png')" },
    { id: 75, name: "Кнопия восьмилепестковая, M /Knopia sp.(Jasmine Polyps)", price: "4 990 ₽", image: "url('../images/image_75.png')" },
    { id: 76, name: "Лобофитум зеленый, SM /Lobophytum aasp(green).", price: "5 000 ₽", image: "url('../images/image_76.jpg')" },
    { id: 77, name: "Синулярия, L /Sinularia sp.(colored) КЕНИЯ", price: "5 900 ₽", image: "url('../images/image_77.png')" },
    { id: 78, name: "Саркофитон (цветной), M /Sarcophyton aasp. (coloured)", price: "7 000 ₽", image: "url('../images/image_78.png')" },
    { id: 79, name: "Синулярия зеленая кудрявая, M /Sinularia sp.(Green Finger Curly)", price: "4 000 ₽", image: "url('../images/image_79.png')" },
    { id: 80, name: "Родактис волосатый зеленый, М/L /Rhodactis indosinensis (green) КЕНИЯ", price: "5 900 ₽", image: "url('../images/image_80.png')" },
    { id: 81, name: "Саркофитон зеленый, L /Sarcophyton sp.(Green) КЕНИЯ", price: "6 900 ₽", image: "url('../images/image_81.png')" },
    { id: 82, name: "Синулярия узкопалая, М /Sinularia flexibilis", price: "3 000 ₽", image: "url('../images/image_82.png')" },
    { id: 83, name: "Камень &#171;живой&#187; ПРЕМИУИМ (плоские)/Live rock", price: " ₽", image: "url('../images/image_83.png')" },
    { id: 84, name: "Актиния ковровая мини (ассорти), M/Stichodactyla Tapetum (Mini Carpet Assorted).", price: "4 990 ₽", image: "url('../images/image_84.jpg')", htmlId: "invertebrates" },
    { id: 85, name: "Актиния пузырчатая красно-зеленая, M/L /Entacmaea quadricolor.", price: "5 990 ₽", image: "url('../images/image_85.png')" },
    { id: 86, name: "Актиния роскошная пурпурная, XL/Heteractis Magnifica (Purple).", price: "11 000 ₽", image: "url('../images/image_86.jpg')" },
    { id: 87, name: "Актиния роскошная зеленая, L /Heteractis magnifica(green).", price: "9 990 ₽", image: "url('../images/image_87.jpg')" },
    { id: 88, name: "Актиния ковровая зеленая, XL/Stichodactyla Gigantea(Metallic Green)", price: "12 900 ₽", image: "url('../images/image_88.png')" },
    { id: 89, name: "Актиния ковровая зеленый металлик, XXL/Stichodactyla Gigantea(Metallic Green).", price: "27 000 ₽", image: "url('../images/image_89.jpg')" },
    { id: 90, name: "Цериантус оранжевый, M /Cerianthus membranaceus (Orange)", price: "4 990 ₽", image: "url('../images/image_90.png')" },
    { id: 91, name: "Цериантус розовый с зелёным центром, M /Cerianthus membranaceus (Pinc+ Green).", price: "4 990 ₽", image: "url('../images/image_91.jpg')" },
    { id: 92, name: "Морская губка оранжевая/Stylotella Aurontium", price: "3 990 ₽", image: "url('../images/image_92.png')" },
    { id: 93, name: "Звезда морская песочная, S/М/Archaster typicus", price: "1 100 ₽", image: "url('../images/image_93.png')" },
    { id: 94, name: "Морская звезда Мультифлора, S/М /Linckia Multiflora", price: "1 100 ₽", image: "url('../images/image_94.png')" },
    { id: 95, name: "Звезда морская фромия, M /Fromia sp.", price: "1 990 ₽", image: "url('../images/image_95.png')" },
    { id: 96, name: "Морская звезда новой каледонии, M/Nardoa novaecaledoniae", price: "1 590 ₽", image: "url('../images/image_96.png')" },
    { id: 97, name: "Звезда морская генеральская красная, М / Protoreaster lincki.", price: "1 990 ₽", image: "url('../images/image_97.jpg')" },
    { id: 98, name: "Звезда морская генеральская цветная, М /Pentaceraster alveolatus", price: "1 390 ₽", image: "url('../images/image_98.png')" },
    { id: 99, name: "Морская звезда фромия красная, М /Fromia monilis (red)", price: "1 790 ₽", image: "url('../images/image_99.png')" },
    { id: 100, name: "Звезда морская линкия красная, XL /Linckia Sp. (Red Batik Linkia Star Fish) КЕНИЯ", price: "3 990 ₽", image: "url('../images/image_100.png')" },
    { id: 101, name: "Офиура зеленая, М /Ophiaracna incrassata.", price: "890 ₽", image: "url('../images/image_101.png')" },
    { id: 102, name: "Офиура черная, М /Ophiocoma echinata (black)", price: "890 ₽", image: "url('../images/image_102.png')" },
    { id: 103, name: "Офиура зеленая, М /Ophiaracna incrassata.", price: "890 ₽", image: "url('../images/image_103.png')" },
    { id: 104, name: "Еж черный оранжевоглазый длинноиглый, M /Diadema setosum", price: "1 290 ₽", image: "url('../images/image_104.jpg')" },
    { id: 105, name: "Еж морской Песчаный доллар, M /Clypeaster australasiae", price: "1 590 ₽", image: "url('../images/image_105.png')" },
    { id: 106, name: "Еж короткоиглый(&#171;арбуз&#187;) (иглокожие), М /Mespilia globulus", price: "1 290 ₽", image: "url('../images/image_106.jpg')" },
    { id: 107, name: "Еж морской пурпурный, М /Echlonometra sp. (Purple)", price: "1 100 ₽", image: "url('../images/image_107.png')" },
    { id: 108, name: "Ёж морской розовый.", price: "1 000 ₽", image: "url('../images/image_108.png')" },
    { id: 109, name: "Еж Эхинометра скаловерт, М /Echinometra mathaei", price: "1 100 ₽", image: "url('../images/image_109.png')" },
    { id: 110, name: "Еж короткоиглый цветной (иглокожие). /Tripneustes gratilla", price: "M - 990/ L - 1 300 ₽", image: "url('../images/image_110.png')" },
    { id: 111, name: "Еж длинноиглый каламарис. L /Echinothrix Calamaris", price: "1 490 ₽", image: "url('../images/image_111.png')" },
    { id: 112, name: "Лилия Морская, М /Comatula spp.", price: "4 990 ₽", image: "url('../images/image_112.jpg')" },
    { id: 113, name: "Кривохвостка обыкновенная (Морская уточка)/Aeoliscus strigatus", price: "1 990 ₽", image: "url('../images/image_113.jpg')" },
    { id: 114, name: "Спиральный червь в известковой трубке, L /Protula bispiralis (red).", price: "4 990 ₽", image: "url('../images/image_114.jpg')" },
    { id: 115, name: "Спиральный червь в известковой трубке, L /Protula bispiralis (red).", price: "4 990 ₽", image: "url('../images/image_115.jpg')" },
    { id: 116, name: "Червь веерный желтый, М/Spirographis spallanzanii (Yellow).", price: "1 200 ₽", image: "url('../images/image_116.jpg')" },
    { id: 117, name: "Голотурия красно-коричневая, M/Cucumaria miniata (Red - Brown)", price: "1 100 ₽", image: "url('../images/image_117.jpg')" },
    { id: 118, name: "Заяц морской (голожаберные молюски), /Dolabella auricularia", price: "S - 1 190/M - 1 290 ₽ ₽", image: "url('../images/image_118.jpg')" },
    { id: 119_1, name: "Тридакна/Tridacna crocea", price: "S - 7 990 ₽", image: "url('../images/image_119.jpg')" },
    { id: 119_2, name: "Тридакна/Tridacna crocea", price: "M - 8 990/L - 9 990 ₽", image: "url('../images/image_119.jpg')" },
    { id: 120, name: "Стромбус черноротый, M /Strombus urceus", price: "500 ₽", image: "url('../images/image_120.jpg')" },
    { id: 121, name: "Улитка Нассариус, M /Nassarius Snail  M", price: "500 ₽", image: "url('../images/image_121.jpg')" },
    { id: 122, name: "Улитка Трохус, M /Trochus maculatus.", price: "500 ₽", image: "url('../images/image_122.jpg')" },
    { id: 123, name: "Улитка Церитий, M /Cerithium spp. КЕНИЯ", price: "500 ₽", image: "url('../images/image_123.jpg')" },
    { id: 124, name: "Улитка турбо оранжевая, M /Buccinulum corneum", price: "500 ₽", image: "url('../images/image_124.jpg')" },
    { id: 125, name: "Улитка-волчок, M /Tectus fenestratus M.", price: "500 ₽", image: "url('../images/image_125.jpg')" },
    { id: 126, name: "Улитка насариус, M /Nassarius Snail M", price: "500 ₽", image: "url('../images/image_126.jpg')" },
    { id: 127, name: "Рак-отшельник оранжево-красный, М /Clibanarius rutilus.", price: "500 ₽", image: "url('../images/image_127.jpg')" },
    { id: 128, name: "Улитка трохус Пирамис, M /Trochus pyramis", price: "500 ₽", image: "url('../images/image_128.jpg')" },
    { id: 129, name: "Ципрея тигровая, M/L /Cypraea tigris", price: "990 ₽", image: "url('../images/image_129.jpg')" },
    { id: 130, name: "Скутус черный (голожаберные моллюски), M /Scutus unguis (Black Limpet)", price: "500 ₽", image: "url('../images/image_130.jpg')" },
    { id: 131, name: "Креветка-доктор Вурдеманна, M/ Lysmata wurdemanni", price: "1 900 ₽", image: "url('../images/image_131.jpg')", htmlId: "arthropods" },
    { id: 132, name: "Креветка Альфеус желтополосая, M/ Alpheus lobidens", price: "1 190 ₽", image: "url('../images/image_132.png')" },
    { id: 133, name: "Креветка анемоновая белоточечная, М /Periclimenes brevicarpalis", price: "1 590 ₽", image: "url('../images/image_133.png')" },
    { id: 134, name: "Креветка сексуальная (членистоногие), М /Thor amboinensis", price: "1 790 ₽", image: "url('../images/image_134.jpg')" },
    { id: 135, name: "Креветка кровавая, M /Lysmata debelius", price: "2 400 ₽", image: "url('../images/image_135.png')" },
    { id: 136, name: "Креветка - чистильщик, М /Lysmata amboinensis", price: "1 890 ₽", image: "url('../images/image_136.png')" },
    { id: 137, name: "Креветка - верблюд (членистоногие), М /Rhynchocinetes durbanensis.", price: "990 ₽", image: "url('../images/image_137.jpg')" },
    { id: 138, name: "Краб декоратор, M/ Oregonia sp", price: "1 390 ₽", image: "url('../images/image_138.png')" },
    { id: 139, name: "Рак-богомол цветной, полосатый/Odontodactylus scyllarus", price: "S - 1 790/ M - 2 990 ₽", image: "url('../images/image_139.png')" },
    { id: 140, name: "Рак-отшельник синелапый, М /Calcinus elegans.", price: "500 ₽", image: "url('../images/image_140.jpg')" },
    { id: 141, name: "Рак-отшельник большой красный, L /Dardanus megistos КЕНИЯ", price: "2 490 ₽", image: "url('../images/image_141.png')" },
    { id: 142, name: "Рак-отшельник оранжеволапый", price: "500 ₽", image: "url('../images/image_142.png')" },
    { id: 143, name: "Краб фарфоровый (анемоновый)", price: "1 990 ₽", image: "url('../images/image_143.png')" },
    { id: 144, name: "Краб коралловый красный, М / Trapezia lutea", price: "1 790 ₽", image: "url('../images/image_144.png')" },
    { id: 145, name: "Краб клубничный, М/Neoliomera pubescens.", price: "1 990 ₽", image: "url('../images/image_145.jpg')" },
    { id: 146, name: "Краб анемоновый помпоновый (членистоногие), М /Lybia tesselata", price: "1 590 ₽", image: "url('../images/image_146.png')" },
    { id: 147, name: "Акула черноперая рифовая М /Carcharhinus melanopterus (50-60 см)", price: "169 000 ₽", image: "url('../images/image_147.png')", htmlId: "fish" },
    { id: 148, name: "Ангел карликовый двухцветный", price: "M - 1 990/L - 2 190 ₽", image: "url('../images/image_148.png')" },
    { id: 149, name: "Ангел карликовый желтоплавничный, М /Centropyge flavipectoralis.", price: "1 590 ₽", image: "url('../images/image_149.png')" },
    { id: 150, name: "Ангел карликовый африканский, М /Centropyge Acanthops (КЕНИЯ)", price: "4 990 ₽", image: "url('../images/image_150.png')" },
    { id: 151, name: "Ангел карликовый полосатый, М /Paracentropyge multifasciata.", price: "5 990 ₽", image: "url('../images/image_151.png')" },
    { id: 152, name: "Ангел Навары(взрослый), S/Pomacanthus navarchus (a)", price: "8 990 ₽", image: "url('../images/image_152.png')" },
    { id: 153, name: "Ангел императорский (ювенильный), М /Pomacanthus imperator (j).", price: "5 990 ₽", image: "url('../images/image_153.png')" },
    { id: 154, name: "Ангел императорский (взрослый)/Pomacanthus imperator (a).", price: "L - 9 990/XXL - 35 000 ₽", image: "url('../images/image_154.png')" },
    { id: 155, name: "Ангел кольчатый (ювенильный), M /Pomacanthus annularis (j)", price: "10 990 ₽", image: "url('../images/image_155.png')" },
    { id: 156, name: "Ангел царский(взрослый), L /Pygoplites diacanthus (a).", price: "12 900 ₽", image: "url('../images/image_156.png')" },
    { id: 157, name: "Ангел рябой (семициркулятус) ювенильный, L/Pomacanthus semicirculatus (j)", price: "7 990 ₽", image: "url('../images/image_157.png')" },
    { id: 158, name: "Ангел Арабский/Pomacanthus asfur", price: "M - 14 990/L - 17 990 ₽", image: "url('../images/image_158.png')" },
    { id: 159, name: "Антиас обыкновенный полиприон(самка), M /Pseudanthias squamipinnis (f).", price: "1 490 ₽", image: "url('../images/image_159.png')" },
    { id: 160, name: "Антиас пламенный, М /Pseudanthias ignitus", price: "1 990 ₽", image: "url('../images/image_160.png')" },
    { id: 161, name: "Антиас персиковый самка/самец, M /Pseudanthias dispar (f)", price: "990 ₽", image: "url('../images/image_161.png')" },
    { id: 162, name: "Антиас двупятнистый(самка), M /Pseudanthias bimaculatus(female)", price: "2 990 ₽", image: "url('../images/image_162.png')" },
    { id: 163, name: "Антиас Купера., M /Pseudanthias Cooperi", price: "2 990 ₽", image: "url('../images/image_163.png')" },
    { id: 164, name: "Антиас - бурбон, M /Odontanthias Borbonius", price: "24 000 ₽", image: "url('../images/image_164.png')" },
    { id: 165, name: "Апогон голубоглазый, M /Apogon leptacanthus", price: "550 ₽", image: "url('../images/image_165.png')" },
    { id: 166, name: "Апогон каудерна тюлевый, M /Pterapogon kauderni", price: "1 390 ₽", image: "url('../images/image_166.png')" },
    { id: 167, name: "Апогон кардинал пижама, М/ Sphaeramia nematoptera", price: "790 ₽", image: "url('../images/image_167.png')" },
    { id: 168, name: "Бабочка Аурига/Chaetodon auriga КЕНИЯ", price: "S - 2 990/L - 3 290/M - 3 990 ₽", image: "url('../images/image_168.png')" },
    { id: 169, name: "Бабочка пирамидальная черная, M/L/Hemitaurichthys zoster", price: "4 990 ₽", image: "url('../images/image_169.png')" },
    { id: 170, name: "Бабочка - пинцет хелмон, M /Chelmon rostratus.", price: "4 590 ₽", image: "url('../images/image_170.png')" },
    { id: 171, name: "Бабочка - пинцет желтая/Forcipiger flavissimus", price: "M - 4 900 ₽/L - 5 500 ₽", image: "url('../images/image_171.png')" },
    { id: 172, name: "Бабочка-Гемитаурихт пирамидальный, М/L / Hemitaurichthys Polylepis.", price: "8 900 ₽", image: "url('../images/image_172.png')" },
    { id: 173, name: "Бабочка пакистанская краснохвостая, S/M /Chaetodon collare.", price: "3 590 ₽", image: "url('../images/image_173.png')" },
    { id: 174, name: "Бабочка-серп, M /Chaetodon falcula", price: "3 590 ₽", image: "url('../images/image_174.png')" },
    { id: 175, name: "Бабочка вымпельная белоперая, S /Heniochus acuminatus.", price: "2 990 ₽", image: "url('../images/image_175.png')" },
    { id: 176, name: "Бабочка трехполосая красноплавничная, M /Chaetodon trifasciatus.", price: "2 790 ₽", image: "url('../images/image_176.png')" },
    { id: 177, name: "Бабочка желтоголовая, М /Chaetodon xanthocephalus.", price: "2 790 ₽", image: "url('../images/image_177.png')" },
    { id: 178, name: "Бабочка африканская, M /Chaetodon dolosus", price: "9 000 ₽", image: "url('../images/image_178.png')" },
    { id: 179, name: "Барабуля золотая М /Parupeneus cyclostomus.", price: "2 490 ₽", image: "url('../images/image_179.png')" },
    { id: 180, name: "Бычок золотоголовый, M /Valenciennea strigata M КЕНИЯ", price: "1 390 ₽", image: "url('../images/image_180.png')" },
    { id: 181, name: "Бычок Нематэлеотрис роскошный, M /Nemateleotris magnifica", price: "3 990 ₽", image: "url('../images/image_181.jpg')" },
    { id: 182, name: "Бычок вива краснопятнистый, М / Parapercis cephalopunctata", price: "1 490 ₽", image: "url('../images/image_182.jpg')" },
    { id: 183, name: "Бычок вива краснопятнистый, L / Parapercis cephalopunctata", price: "1 690 ₽", image: "url('../images/image_183.png')" },
    { id: 184, name: "Бычок двухполосый, М /Valenciennea helsdingeni", price: "1 490 ₽", image: "url('../images/image_184.png')" },
    { id: 185, name: "Нематэлеотрис пурпурный , M /Nemateleotris decora", price: "3 990 ₽", image: "url('../images/image_185.jpg')" },
    { id: 186, name: "Групер коричневый синеполосый, M /Cephalopholis beonack", price: "2 490 ₽", image: "url('../images/image_186.png')" },
    { id: 187, name: "Групер черноточечный, L /Cromileptes altivelis.", price: "6 500 ₽", image: "url('../images/image_187.png')" },
    { id: 188, name: "Губан-доктор, M /Labroides dimidiatus.", price: "1 200 ₽", image: "url('../images/image_188.png')" },
    { id: 189, name: "Губан тамарин банановый , M /Halichoeres chrysus.", price: "1 490 ₽", image: "url('../images/image_189.png')" },
    { id: 190, name: "Губан тамарин зеленый (взрослый), M/ Halichoeres chloropterus (a)", price: "1 390 ₽", image: "url('../images/image_190.png')" },
    { id: 191, name: "Губан сверкающий Маккоскера, М /Paracheilinus mccoskeri", price: "3 990 ₽", image: "url('../images/image_191.jpg')" },
    { id: 192, name: "Губан рубрис, M /Cirrhilabrus rubrisquamis", price: "1 990 ₽", image: "url('../images/image_192.png')" },
    { id: 193, name: "Губан двухточечный, M /Cheilinus bimaculatus КЕНИЯ", price: "3 990 ₽", image: "url('../images/image_193.png')" },
    { id: 194, name: "Губан-исчезающий, M /Pseudocheilinus evanidus", price: "990 ₽", image: "url('../images/image_194.jpg')" },
    { id: 195, name: "Тамарин украшенный, M /Halichoeres cosmetus", price: "3 900 ₽", image: "url('../images/image_195.jpg')" },
    { id: 196, name: "Губан бодианус-диана(взрослый), M /Bodianus diana", price: "3 990 ₽", image: "url('../images/image_196.png')" },
    { id: 197, name: "Губан-клюворыл(самец), M  /Gomphosus caeruleus (m)", price: "3 990 ₽", image: "url('../images/image_197.png')" },
    { id: 198, name: "Губан бодиан лирохвостый (антоидес), М /Bodianus anthioides.", price: "5 990 ₽", image: "url('../images/image_198.png')" },
    { id: 199, name: "Губан африканский длинноперый сказочный, М/Cirrhilabrus africanus", price: "13 000 ₽", image: "url('../images/image_199.jpg')" },
    { id: 200, name: "Талассома лунная(самец), XL /Thalassoma lunare (m)", price: "2 900 ₽", image: "url('../images/image_200.png')" },
    { id: 201, name: "Иглобрюх-тоби Валентина, M /Canthigaster valentini", price: "1 590 ₽", image: "url('../images/image_201.png')" },
    { id: 202, name: "Иглобрюх Беннетта, М /Canthigaster bennetti.", price: "1 590 ₽", image: "url('../images/image_202.png')" },
    { id: 203, name: "Аротрон безупречный желтоглазый, L /Arothron Immaculatus", price: "17 990 ₽", image: "url('../images/image_203.png')" },
    { id: 204, name: "Аротрон черно-пятнистый, L /Arothron nigropunctatus.", price: "9 900 ₽", image: "url('../images/image_204.png')" },
    { id: 205, name: "Аротрон звезчатый, M /Arothron stellatus КЕНИЯ.", price: "9 000 ₽", image: "url('../images/image_205.png')" },
    { id: 206, name: "Рыба-еж длинноиглая, L /Diodon holocanthus.", price: "5 500 ₽", image: "url('../images/image_206.png')" },
    { id: 207, name: "Кудрепер Бликера, M /Cirrhitichthys bleekeri", price: "1 590 ₽", image: "url('../images/image_207.png')" },
    { id: 208, name: "Кузовок кубик/Ostracion cubicus.", price: "S - 2 590/M - 2 590 ₽", image: "url('../images/image_208.jpg')" },
    { id: 209, name: "Кузовок пятнистый (самка), L/Ostracion meleagris (f).", price: "6 990 ₽", image: "url('../images/image_209.png')" },
    { id: 210, name: "Кузовок рыжий нос, M /Ostracion rhinorhynchos.", price: "3 790 ₽", image: "url('../images/image_210.png')" },
    { id: 211, name: "Ложнохромис королевский, М /Pseudochromis Paccagnelae", price: "1 590 ₽", image: "url('../images/image_211.png')" },
    { id: 212, name: "Луциан императорский красный, M /Lutjanus sebae.", price: "8 990 ₽", image: "url('../images/image_212.jpg')" },
];

// { id: 1, name: "", price: " ₽", image: "url('../images/image_1.png')" },
// or jpg. Better to use the same on everyone!
// &#171; кавычки &#187;

function generateProductCard(product) {
    const idAttribute = product.htmlId ? ` id="${product.htmlId}"` : "";
    return `
        <div class="swiper-slide _${product.id}" ${idAttribute} style="background-image: linear-gradient(180deg, rgba(2, 61, 116, 0) 47.9%, #023D74 86.9%), ${product.image};">
            <h3>${product.name}</h3>
            <p>${product.price}</p>
        </div>
    `;
}

document.addEventListener("DOMContentLoaded", function () {
    const productContainer = document.getElementById("product-container");
    products.forEach(product => {
        const cardHTML = generateProductCard(product);
        productContainer.innerHTML += cardHTML;
    });
});




